version: '3.4'

services:
  db:
    container_name: db
    image: mysql:5.7.30
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "books-api"
    ports:
      - 3306:3306

  books-api:
    container_name: books-api
    build:
      context: .
      dockerfile: "./DockerfileDev"
    volumes:
      - ./src:/home/app/src
      - /home/app/node_modules
    image: books-api
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306
    ports:
      - 3333:3333
